//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DBoleta {
            get {
                return ResourceManager.GetString("DBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DBoletaConcepto {
            get {
                return ResourceManager.GetString("DBoletaConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DBoletaFecha {
            get {
                return ResourceManager.GetString("DBoletaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagen_del_colegio_MLP {
            get {
                object obj = ResourceManager.GetObject("imagen del colegio MLP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string KDeterminadoAlumno {
            get {
                return ResourceManager.GetString("KDeterminadoAlumno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string KDeterminadoGrado {
            get {
                return ResourceManager.GetString("KDeterminadoGrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string KGeneral {
            get {
                return ResourceManager.GetString("KGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string RAdeudoresfecha {
            get {
                return ResourceManager.GetString("RAdeudoresfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RAdeudoresfechagrado {
            get {
                return ResourceManager.GetString("RAdeudoresfechagrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string RAgrado {
            get {
                return ResourceManager.GetString("RAgrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web Page Desing &lt;/title&gt;
        ///    &lt;style&gt;
        ///            table.border {
        ///            border-collapse: collapse;
        ///             }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///            .emoji {
        ///                font-size: 2em;/*&lt;title&gt;Web Page Desing &lt;span class=&quot;emoji&quot;&gt;&amp;#x1F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RApensionesmesgrado {
            get {
                return ResourceManager.GetString("RApensionesmesgrado", resourceCulture);
            }
        }
    }
}
